// <auto-generated />
namespace CMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Manager5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manager5));
        
        string IMigrationMetadata.Id
        {
            get { return "202109220026225_Manager5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
