// <auto-generated />
namespace CMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Manager2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manager2));
        
        string IMigrationMetadata.Id
        {
            get { return "202109200255208_Manager2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
